name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install thumbv6m-none-eabi target
      run: rustup target add thumbv6m-none-eabi
    - name: Build
      working-directory: ./firmware
      run: cargo build --verbose
